### ISSUE TITLE
可能不支持坐山听风老师的所有作品 Uncaught Error Error: TNaN is not a valid duration.

### ISSUE THREAD

**Issue by weypro** [ThebestkillerTBK/chongchong-free#8]
如题，具体报错如下
```
Uncaught Error Error: TNaN is not a valid duration.
    at getTickDuration (e:\chongchong-free-master\node_modules\midi-writer-js\build\index.js:355:17)
    at NoteEvent (e:\chongchong-free-master\node_modules\midi-writer-js\build\index.js:794:31)
    at writeMIDI (e:\chongchong-free-master\libCCMZ.js:148:20)
    at writeAndConvert (e:\chongchong-free-master\functions.js:26:17)
    at <anonymous> (e:\chongchong-free-master\libCCMZ.js:56:17)
```
原因是`MidiWriter.NoteEvent`的`mDuration`为`undefined`
进一步向上溯源
```
if (tick === thisTick) {
              mDuration = baseMultiplier * lastTempo / currTempo;
              mTick = baseMultiplier * lastTempo / currTempo;
            }
```
因为在此处`if (tick === thisTick) `为假，所以直接跳过了`mDuration`的赋值
因为我看不懂这段代码为何要这样计算所以也没法改，除了这位老师的作品外又测试了其他几首，复杂一点的作品速度就有问题了
如果作者能补完核心代码的注释那就好了

**Comment by yjwu** [comment]
[line 123](https://github.com/Fiz-Vector/chongchong-free/blob/55004a7f924b6329366a46ea4dad0b95c059941e/libCCMZ.js#L123) 处 `mDuration` 创建时未初始化； 初始赋为`baseMultiplier`就好了~
